package ssi.g3.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Establishment.proto

public final class StationToStation {
  private StationToStation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EstablishmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Establishment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes gx = 1;</code>
     */
    com.google.protobuf.ByteString getGx();
  }
  /**
   * Protobuf type {@code Establishment}
   */
  public  static final class Establishment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Establishment)
      EstablishmentOrBuilder {
    // Use Establishment.newBuilder() to construct.
    private Establishment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Establishment() {
      gx_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Establishment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              gx_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StationToStation.internal_static_Establishment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StationToStation.internal_static_Establishment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StationToStation.Establishment.class, StationToStation.Establishment.Builder.class);
    }

    public static final int GX_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString gx_;
    /**
     * <code>bytes gx = 1;</code>
     */
    public com.google.protobuf.ByteString getGx() {
      return gx_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!gx_.isEmpty()) {
        output.writeBytes(1, gx_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!gx_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, gx_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StationToStation.Establishment)) {
        return super.equals(obj);
      }
      StationToStation.Establishment other = (StationToStation.Establishment) obj;

      boolean result = true;
      result = result && getGx()
          .equals(other.getGx());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GX_FIELD_NUMBER;
      hash = (53 * hash) + getGx().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StationToStation.Establishment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.Establishment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.Establishment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.Establishment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.Establishment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.Establishment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.Establishment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationToStation.Establishment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationToStation.Establishment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StationToStation.Establishment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationToStation.Establishment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationToStation.Establishment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StationToStation.Establishment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Establishment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Establishment)
        StationToStation.EstablishmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StationToStation.internal_static_Establishment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StationToStation.internal_static_Establishment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StationToStation.Establishment.class, StationToStation.Establishment.Builder.class);
      }

      // Construct using StationToStation.Establishment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gx_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StationToStation.internal_static_Establishment_descriptor;
      }

      public StationToStation.Establishment getDefaultInstanceForType() {
        return StationToStation.Establishment.getDefaultInstance();
      }

      public StationToStation.Establishment build() {
        StationToStation.Establishment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StationToStation.Establishment buildPartial() {
        StationToStation.Establishment result = new StationToStation.Establishment(this);
        result.gx_ = gx_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StationToStation.Establishment) {
          return mergeFrom((StationToStation.Establishment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StationToStation.Establishment other) {
        if (other == StationToStation.Establishment.getDefaultInstance()) return this;
        if (other.getGx() != com.google.protobuf.ByteString.EMPTY) {
          setGx(other.getGx());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StationToStation.Establishment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StationToStation.Establishment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString gx_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes gx = 1;</code>
       */
      public com.google.protobuf.ByteString getGx() {
        return gx_;
      }
      /**
       * <code>bytes gx = 1;</code>
       */
      public Builder setGx(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes gx = 1;</code>
       */
      public Builder clearGx() {
        
        gx_ = getDefaultInstance().getGx();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Establishment)
    }

    // @@protoc_insertion_point(class_scope:Establishment)
    private static final StationToStation.Establishment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StationToStation.Establishment();
    }

    public static StationToStation.Establishment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Establishment>
        PARSER = new com.google.protobuf.AbstractParser<Establishment>() {
      public Establishment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Establishment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Establishment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Establishment> getParserForType() {
      return PARSER;
    }

    public StationToStation.Establishment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeyAndCertOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeyAndCert)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes gy = 1;</code>
     */
    com.google.protobuf.ByteString getGy();

    /**
     * <code>bytes cert = 2;</code>
     */
    com.google.protobuf.ByteString getCert();

    /**
     * <code>bytes sign = 3;</code>
     */
    com.google.protobuf.ByteString getSign();

    /**
     * <code>bytes iv = 4;</code>
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>bytes mac = 5;</code>
     */
    com.google.protobuf.ByteString getMac();
  }
  /**
   * Protobuf type {@code KeyAndCert}
   */
  public  static final class KeyAndCert extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KeyAndCert)
      KeyAndCertOrBuilder {
    // Use KeyAndCert.newBuilder() to construct.
    private KeyAndCert(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyAndCert() {
      gy_ = com.google.protobuf.ByteString.EMPTY;
      cert_ = com.google.protobuf.ByteString.EMPTY;
      sign_ = com.google.protobuf.ByteString.EMPTY;
      iv_ = com.google.protobuf.ByteString.EMPTY;
      mac_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private KeyAndCert(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              gy_ = input.readBytes();
              break;
            }
            case 18: {

              cert_ = input.readBytes();
              break;
            }
            case 26: {

              sign_ = input.readBytes();
              break;
            }
            case 34: {

              iv_ = input.readBytes();
              break;
            }
            case 42: {

              mac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StationToStation.internal_static_KeyAndCert_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StationToStation.internal_static_KeyAndCert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StationToStation.KeyAndCert.class, StationToStation.KeyAndCert.Builder.class);
    }

    public static final int GY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString gy_;
    /**
     * <code>bytes gy = 1;</code>
     */
    public com.google.protobuf.ByteString getGy() {
      return gy_;
    }

    public static final int CERT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString cert_;
    /**
     * <code>bytes cert = 2;</code>
     */
    public com.google.protobuf.ByteString getCert() {
      return cert_;
    }

    public static final int SIGN_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString sign_;
    /**
     * <code>bytes sign = 3;</code>
     */
    public com.google.protobuf.ByteString getSign() {
      return sign_;
    }

    public static final int IV_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString iv_;
    /**
     * <code>bytes iv = 4;</code>
     */
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int MAC_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>bytes mac = 5;</code>
     */
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!gy_.isEmpty()) {
        output.writeBytes(1, gy_);
      }
      if (!cert_.isEmpty()) {
        output.writeBytes(2, cert_);
      }
      if (!sign_.isEmpty()) {
        output.writeBytes(3, sign_);
      }
      if (!iv_.isEmpty()) {
        output.writeBytes(4, iv_);
      }
      if (!mac_.isEmpty()) {
        output.writeBytes(5, mac_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!gy_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, gy_);
      }
      if (!cert_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, cert_);
      }
      if (!sign_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, sign_);
      }
      if (!iv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, iv_);
      }
      if (!mac_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, mac_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StationToStation.KeyAndCert)) {
        return super.equals(obj);
      }
      StationToStation.KeyAndCert other = (StationToStation.KeyAndCert) obj;

      boolean result = true;
      result = result && getGy()
          .equals(other.getGy());
      result = result && getCert()
          .equals(other.getCert());
      result = result && getSign()
          .equals(other.getSign());
      result = result && getIv()
          .equals(other.getIv());
      result = result && getMac()
          .equals(other.getMac());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GY_FIELD_NUMBER;
      hash = (53 * hash) + getGy().hashCode();
      hash = (37 * hash) + CERT_FIELD_NUMBER;
      hash = (53 * hash) + getCert().hashCode();
      hash = (37 * hash) + SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getSign().hashCode();
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StationToStation.KeyAndCert parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.KeyAndCert parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.KeyAndCert parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.KeyAndCert parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.KeyAndCert parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.KeyAndCert parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.KeyAndCert parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationToStation.KeyAndCert parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationToStation.KeyAndCert parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StationToStation.KeyAndCert parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationToStation.KeyAndCert parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationToStation.KeyAndCert parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StationToStation.KeyAndCert prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyAndCert}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeyAndCert)
        StationToStation.KeyAndCertOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StationToStation.internal_static_KeyAndCert_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StationToStation.internal_static_KeyAndCert_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StationToStation.KeyAndCert.class, StationToStation.KeyAndCert.Builder.class);
      }

      // Construct using StationToStation.KeyAndCert.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gy_ = com.google.protobuf.ByteString.EMPTY;

        cert_ = com.google.protobuf.ByteString.EMPTY;

        sign_ = com.google.protobuf.ByteString.EMPTY;

        iv_ = com.google.protobuf.ByteString.EMPTY;

        mac_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StationToStation.internal_static_KeyAndCert_descriptor;
      }

      public StationToStation.KeyAndCert getDefaultInstanceForType() {
        return StationToStation.KeyAndCert.getDefaultInstance();
      }

      public StationToStation.KeyAndCert build() {
        StationToStation.KeyAndCert result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StationToStation.KeyAndCert buildPartial() {
        StationToStation.KeyAndCert result = new StationToStation.KeyAndCert(this);
        result.gy_ = gy_;
        result.cert_ = cert_;
        result.sign_ = sign_;
        result.iv_ = iv_;
        result.mac_ = mac_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StationToStation.KeyAndCert) {
          return mergeFrom((StationToStation.KeyAndCert)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StationToStation.KeyAndCert other) {
        if (other == StationToStation.KeyAndCert.getDefaultInstance()) return this;
        if (other.getGy() != com.google.protobuf.ByteString.EMPTY) {
          setGy(other.getGy());
        }
        if (other.getCert() != com.google.protobuf.ByteString.EMPTY) {
          setCert(other.getCert());
        }
        if (other.getSign() != com.google.protobuf.ByteString.EMPTY) {
          setSign(other.getSign());
        }
        if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
          setIv(other.getIv());
        }
        if (other.getMac() != com.google.protobuf.ByteString.EMPTY) {
          setMac(other.getMac());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StationToStation.KeyAndCert parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StationToStation.KeyAndCert) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString gy_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes gy = 1;</code>
       */
      public com.google.protobuf.ByteString getGy() {
        return gy_;
      }
      /**
       * <code>bytes gy = 1;</code>
       */
      public Builder setGy(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes gy = 1;</code>
       */
      public Builder clearGy() {
        
        gy_ = getDefaultInstance().getGy();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cert_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes cert = 2;</code>
       */
      public com.google.protobuf.ByteString getCert() {
        return cert_;
      }
      /**
       * <code>bytes cert = 2;</code>
       */
      public Builder setCert(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cert_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes cert = 2;</code>
       */
      public Builder clearCert() {
        
        cert_ = getDefaultInstance().getCert();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sign_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes sign = 3;</code>
       */
      public com.google.protobuf.ByteString getSign() {
        return sign_;
      }
      /**
       * <code>bytes sign = 3;</code>
       */
      public Builder setSign(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes sign = 3;</code>
       */
      public Builder clearSign() {
        
        sign_ = getDefaultInstance().getSign();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iv = 4;</code>
       */
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>bytes iv = 4;</code>
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iv = 4;</code>
       */
      public Builder clearIv() {
        
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes mac = 5;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }
      /**
       * <code>bytes mac = 5;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes mac = 5;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:KeyAndCert)
    }

    // @@protoc_insertion_point(class_scope:KeyAndCert)
    private static final StationToStation.KeyAndCert DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StationToStation.KeyAndCert();
    }

    public static StationToStation.KeyAndCert getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeyAndCert>
        PARSER = new com.google.protobuf.AbstractParser<KeyAndCert>() {
      public KeyAndCert parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new KeyAndCert(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KeyAndCert> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyAndCert> getParserForType() {
      return PARSER;
    }

    public StationToStation.KeyAndCert getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CertAndCriptoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CertAndCripto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes certi = 1;</code>
     */
    com.google.protobuf.ByteString getCerti();

    /**
     * <code>bytes cripto = 2;</code>
     */
    com.google.protobuf.ByteString getCripto();

    /**
     * <code>bytes iv = 3;</code>
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>bytes mac = 4;</code>
     */
    com.google.protobuf.ByteString getMac();
  }
  /**
   * Protobuf type {@code CertAndCripto}
   */
  public  static final class CertAndCripto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CertAndCripto)
      CertAndCriptoOrBuilder {
    // Use CertAndCripto.newBuilder() to construct.
    private CertAndCripto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CertAndCripto() {
      certi_ = com.google.protobuf.ByteString.EMPTY;
      cripto_ = com.google.protobuf.ByteString.EMPTY;
      iv_ = com.google.protobuf.ByteString.EMPTY;
      mac_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CertAndCripto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              certi_ = input.readBytes();
              break;
            }
            case 18: {

              cripto_ = input.readBytes();
              break;
            }
            case 26: {

              iv_ = input.readBytes();
              break;
            }
            case 34: {

              mac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StationToStation.internal_static_CertAndCripto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StationToStation.internal_static_CertAndCripto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StationToStation.CertAndCripto.class, StationToStation.CertAndCripto.Builder.class);
    }

    public static final int CERTI_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString certi_;
    /**
     * <code>bytes certi = 1;</code>
     */
    public com.google.protobuf.ByteString getCerti() {
      return certi_;
    }

    public static final int CRIPTO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString cripto_;
    /**
     * <code>bytes cripto = 2;</code>
     */
    public com.google.protobuf.ByteString getCripto() {
      return cripto_;
    }

    public static final int IV_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString iv_;
    /**
     * <code>bytes iv = 3;</code>
     */
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int MAC_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString mac_;
    /**
     * <code>bytes mac = 4;</code>
     */
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!certi_.isEmpty()) {
        output.writeBytes(1, certi_);
      }
      if (!cripto_.isEmpty()) {
        output.writeBytes(2, cripto_);
      }
      if (!iv_.isEmpty()) {
        output.writeBytes(3, iv_);
      }
      if (!mac_.isEmpty()) {
        output.writeBytes(4, mac_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!certi_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, certi_);
      }
      if (!cripto_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, cripto_);
      }
      if (!iv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, iv_);
      }
      if (!mac_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, mac_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StationToStation.CertAndCripto)) {
        return super.equals(obj);
      }
      StationToStation.CertAndCripto other = (StationToStation.CertAndCripto) obj;

      boolean result = true;
      result = result && getCerti()
          .equals(other.getCerti());
      result = result && getCripto()
          .equals(other.getCripto());
      result = result && getIv()
          .equals(other.getIv());
      result = result && getMac()
          .equals(other.getMac());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CERTI_FIELD_NUMBER;
      hash = (53 * hash) + getCerti().hashCode();
      hash = (37 * hash) + CRIPTO_FIELD_NUMBER;
      hash = (53 * hash) + getCripto().hashCode();
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StationToStation.CertAndCripto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.CertAndCripto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.CertAndCripto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.CertAndCripto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.CertAndCripto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StationToStation.CertAndCripto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StationToStation.CertAndCripto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationToStation.CertAndCripto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationToStation.CertAndCripto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StationToStation.CertAndCripto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StationToStation.CertAndCripto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StationToStation.CertAndCripto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StationToStation.CertAndCripto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CertAndCripto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CertAndCripto)
        StationToStation.CertAndCriptoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StationToStation.internal_static_CertAndCripto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StationToStation.internal_static_CertAndCripto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StationToStation.CertAndCripto.class, StationToStation.CertAndCripto.Builder.class);
      }

      // Construct using StationToStation.CertAndCripto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        certi_ = com.google.protobuf.ByteString.EMPTY;

        cripto_ = com.google.protobuf.ByteString.EMPTY;

        iv_ = com.google.protobuf.ByteString.EMPTY;

        mac_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StationToStation.internal_static_CertAndCripto_descriptor;
      }

      public StationToStation.CertAndCripto getDefaultInstanceForType() {
        return StationToStation.CertAndCripto.getDefaultInstance();
      }

      public StationToStation.CertAndCripto build() {
        StationToStation.CertAndCripto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StationToStation.CertAndCripto buildPartial() {
        StationToStation.CertAndCripto result = new StationToStation.CertAndCripto(this);
        result.certi_ = certi_;
        result.cripto_ = cripto_;
        result.iv_ = iv_;
        result.mac_ = mac_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StationToStation.CertAndCripto) {
          return mergeFrom((StationToStation.CertAndCripto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StationToStation.CertAndCripto other) {
        if (other == StationToStation.CertAndCripto.getDefaultInstance()) return this;
        if (other.getCerti() != com.google.protobuf.ByteString.EMPTY) {
          setCerti(other.getCerti());
        }
        if (other.getCripto() != com.google.protobuf.ByteString.EMPTY) {
          setCripto(other.getCripto());
        }
        if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
          setIv(other.getIv());
        }
        if (other.getMac() != com.google.protobuf.ByteString.EMPTY) {
          setMac(other.getMac());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StationToStation.CertAndCripto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StationToStation.CertAndCripto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString certi_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes certi = 1;</code>
       */
      public com.google.protobuf.ByteString getCerti() {
        return certi_;
      }
      /**
       * <code>bytes certi = 1;</code>
       */
      public Builder setCerti(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        certi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes certi = 1;</code>
       */
      public Builder clearCerti() {
        
        certi_ = getDefaultInstance().getCerti();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString cripto_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes cripto = 2;</code>
       */
      public com.google.protobuf.ByteString getCripto() {
        return cripto_;
      }
      /**
       * <code>bytes cripto = 2;</code>
       */
      public Builder setCripto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cripto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes cripto = 2;</code>
       */
      public Builder clearCripto() {
        
        cripto_ = getDefaultInstance().getCripto();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iv = 3;</code>
       */
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>bytes iv = 3;</code>
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iv = 3;</code>
       */
      public Builder clearIv() {
        
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes mac = 4;</code>
       */
      public com.google.protobuf.ByteString getMac() {
        return mac_;
      }
      /**
       * <code>bytes mac = 4;</code>
       */
      public Builder setMac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes mac = 4;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CertAndCripto)
    }

    // @@protoc_insertion_point(class_scope:CertAndCripto)
    private static final StationToStation.CertAndCripto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StationToStation.CertAndCripto();
    }

    public static StationToStation.CertAndCripto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CertAndCripto>
        PARSER = new com.google.protobuf.AbstractParser<CertAndCripto>() {
      public CertAndCripto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CertAndCripto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CertAndCripto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CertAndCripto> getParserForType() {
      return PARSER;
    }

    public StationToStation.CertAndCripto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Establishment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Establishment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyAndCert_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeyAndCert_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CertAndCripto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CertAndCripto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Establishment.proto\"\033\n\rEstablishment\022\n" +
      "\n\002gx\030\001 \001(\014\"M\n\nKeyAndCert\022\n\n\002gy\030\001 \001(\014\022\014\n\004" +
      "cert\030\002 \001(\014\022\014\n\004sign\030\003 \001(\014\022\n\n\002iv\030\004 \001(\014\022\013\n\003" +
      "mac\030\005 \001(\014\"G\n\rCertAndCripto\022\r\n\005certi\030\001 \001(" +
      "\014\022\016\n\006cripto\030\002 \001(\014\022\n\n\002iv\030\003 \001(\014\022\013\n\003mac\030\004 \001" +
      "(\014B\022B\020StationToStationb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Establishment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Establishment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Establishment_descriptor,
        new java.lang.String[] { "Gx", });
    internal_static_KeyAndCert_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_KeyAndCert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeyAndCert_descriptor,
        new java.lang.String[] { "Gy", "Cert", "Sign", "Iv", "Mac", });
    internal_static_CertAndCripto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CertAndCripto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CertAndCripto_descriptor,
        new java.lang.String[] { "Certi", "Cripto", "Iv", "Mac", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
